Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine318"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	end

	config.vm.define "mkaliszcS" do |server|
		server.vm.hostname = "mkaliszcServer"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "file", source: "confs", destination: "$HOME/confs"
		server.vm.provision "shell", path: "scripts/script-provision.sh"
		server.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "mkaliszcS"]
		end
	end
end