Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine318"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	end
	
	config.vm.define "mkaliszcS" do |server|
		server.vm.hostname = "mkaliszcServer"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "mkaliszcS"]
		end
	end

	config.vm.define "mkaliszcSW" do |worker|
		worker.vm.hostname = "mkaliszcServerWorker"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "mkaliszcSW"]
		end
	end
end

# config.vm.provision "file", source: "./test.sh", destination: "script-test.sh"