Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine318"
	config.vm.synced_folder "./tmp", "/vagrant", 
		type: "virtualbox", 
		create: true
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	end
	
	config.vm.define "mkaliszcS" do |server|
		server.vm.hostname = "mkaliszcServer"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "shell", path: "scripts/server-provision.sh"
		server.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "mkaliszcS"]
		end
	end

	config.vm.define "mkaliszcSW" do |worker|
		worker.vm.hostname = "mkaliszcServerWorker"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.provision "shell", path: "scripts/server-worker-provision.sh"
		worker.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "mkaliszcSW"]
		end
	end
end